###05d.SMR_Comorbidities.r

#run setup file
source("01-data_extraction/000.file_paths.r")
source("01-data_extraction/05.setup_SMR_data_extract.r")
library(hablar)
library(ggplot2)
library(stringr)

###Extract total smr01 emergency admissions previous ?3 years, 5 yrs?
##get chi list
upi_list <- readRDS(paste0(folder_data_path, "SLiPBD_upi_list.rds" ))
upi <- upi_list %>% select(mother_upi)
names(upi) <- "MOTHER_UPI"

##Comorbidities lists
Cancer <- c(paste0("C",str_pad(00:09, 2, pad = "0") ), paste0("C", "10":"97")	)
Haematological<- c(paste0("D", 50:89), "O990", "O991")
Heam_excl_anaemia <-  c(paste0("D", 65:89))
Thyroid <- c(paste0("E",str_pad(00:07, 2, pad = "0")), "O992")
Diabetes<- 	c(paste0("E", 10:14), "O240","O241","O242","O243")
Demyelinating_NM<- c(paste0("G", 35:37), paste0("G", 70:73))
Hypertension <-	c(paste0("I", 10:15), "O10")
VTE<-	c("I26", "I80", "I81","I82")
Asthma<-	c("J45", "J46", "O995")
GI_diseases<-	c(paste0("K", 25:28), paste0("K", 50:52), paste0("K", 80:86), "O996")
Liver <-paste0("K", 71:76)
Skin <-c(paste0("L", 10:45),"O997")
Immune_joint_conn <- c("M05", "M06", "M08",paste0("M", 30:35))
Kidney <-	c(paste0("N",str_pad(00:07, 2, pad = "0")) ,paste0("N", 10:15), "N17", "N18", "N19")
pelvic_genital_dis <-	c(paste0("N", 70:77), paste0("N", 80:94),paste0("N", 96:98))

##SMR01####

dbListTables(SMRAConnection,schema=toupper(Sys.info()[["user"]]))
##extract from 2005
data_smr01_comorbs  

##extract from 2005
data_smr04_comorbs 

data_smr02_comorb 
##Identify diagnosis groups and emergency admissions

smr01 <- data_smr01_comorbs %>% 
  mutate(cancer = case_when(substr(main_condition,1,3) %in% Cancer ~1, 
                            substr(other_condition_1,1,3) %in%  Cancer ~1,  
                            substr(other_condition_2,1,3) %in%  Cancer ~1, 
                            substr(other_condition_3,1,3) %in%  Cancer ~1, 
                            substr(other_condition_4,1,3) %in%  Cancer ~1, 
                            substr(other_condition_5,1,3) %in%  Cancer ~1, 
                            T~0)) %>% 
  mutate(haem = case_when(substr(main_condition,1,3) %in% Haematological ~1, 
                          substr(other_condition_1,1,3) %in%  Haematological ~1, 
                          substr(other_condition_2,1,3) %in%  Haematological ~1, 
                          substr(other_condition_3,1,3) %in%  Haematological ~1, 
                          substr(other_condition_4,1,3) %in% Haematological ~1, 
                          substr(other_condition_5,1,3) %in% Haematological ~1, 
                          substr(main_condition,1,4) %in% Haematological ~1, 
                          substr(other_condition_1,1,4) %in%  Haematological ~1, 
                          substr(other_condition_2,1,4) %in%  Haematological ~1, 
                          substr(other_condition_3,1,4) %in%  Haematological ~1, 
                          substr(other_condition_4,1,4) %in% Haematological ~1, 
                          substr(other_condition_5,1,4) %in% Haematological ~1, 
                          T~0), 
         thyroid =case_when(substr(main_condition,1,3) %in% Thyroid ~1, 
                            substr(other_condition_1,1,3) %in%  Thyroid ~1, 
                            substr(other_condition_2,1,3) %in%  Thyroid ~1, 
                            substr(other_condition_3,1,3) %in%  Thyroid ~1, 
                            substr(other_condition_4,1,3) %in% Thyroid ~1, 
                            substr(other_condition_5,1,3) %in% Thyroid ~1, 
                            substr(main_condition,1,4) %in% Thyroid ~1, 
                            substr(other_condition_1,1,4) %in%  Thyroid ~1, 
                            substr(other_condition_2,1,4) %in%  Thyroid ~1, 
                            substr(other_condition_3,1,4) %in%  Thyroid ~1, 
                            substr(other_condition_4,1,4) %in% Thyroid ~1, 
                            substr(other_condition_5,1,4) %in% Thyroid ~1, 
                            T~0), 
         diabetes  = case_when(substr(main_condition,1,3) %in% Diabetes ~1, 
                               substr(other_condition_1,1,3) %in% Diabetes ~1, 
                               substr(other_condition_2,1,3) %in%   Diabetes ~1, 
                               substr(other_condition_3,1,3) %in%   Diabetes ~1, 
                               substr(other_condition_4,1,3) %in%  Diabetes ~1, 
                               substr(other_condition_5,1,3) %in%  Diabetes ~1, 
                               substr(main_condition,1,4) %in% Diabetes ~1, 
                               substr(other_condition_1,1,4) %in% Diabetes ~1, 
                               substr(other_condition_2,1,4) %in%   Diabetes ~1, 
                               substr(other_condition_3,1,4) %in%   Diabetes ~1, 
                               substr(other_condition_4,1,4) %in%  Diabetes ~1, 
                               substr(other_condition_5,1,4) %in%  Diabetes ~1, 
                               T~0),
         demyelinating_NM  = case_when(substr(main_condition,1,3) %in% Demyelinating_NM ~1, 
                                       substr(other_condition_1,1,3) %in% Demyelinating_NM ~1, 
                                       substr(other_condition_2,1,3) %in%  Demyelinating_NM ~1, 
                                       substr(other_condition_3,1,3) %in%  Demyelinating_NM ~1, 
                                       substr(other_condition_4,1,3) %in%  Demyelinating_NM ~1, 
                                       substr(other_condition_5,1,3) %in% Demyelinating_NM ~1, 
                                       T~0),
         hypertension  = case_when(substr(main_condition,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_1,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_2,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_3,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_4,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_5,1,3) %in% Hypertension ~1, 
                                   T~0),
         vte  = case_when(substr(main_condition,1,3) %in% VTE ~1, 
                          substr(other_condition_1,1,3) %in% VTE ~1, 
                          substr(other_condition_2,1,3) %in% VTE ~1, 
                          substr(other_condition_3,1,3) %in% VTE ~1, 
                          substr(other_condition_4,1,3) %in% VTE ~1, 
                          substr(other_condition_5,1,3) %in%  VTE ~1,  
                          T~0),
         asthma  = case_when(substr(main_condition,1,3) %in% Asthma ~1, 
                             substr(other_condition_1,1,3) %in% Asthma ~1, 
                             substr(other_condition_2,1,3) %in%  Asthma ~1, 
                             substr(other_condition_3,1,3) %in%  Asthma ~1, 
                             substr(other_condition_4,1,3) %in%  Asthma ~1, 
                             substr(other_condition_5,1,3) %in%  Asthma ~1, 
                             substr(main_condition,1,4) %in% Asthma ~1, 
                             substr(other_condition_1,1,4) %in% Asthma ~1, 
                             substr(other_condition_2,1,4) %in%  Asthma ~1, 
                             substr(other_condition_3,1,4) %in%  Asthma ~1, 
                             substr(other_condition_4,1,4) %in%  Asthma ~1, 
                             substr(other_condition_5,1,4) %in%  Asthma ~1, 
                             T~0),
               gi_disease  = case_when(substr(main_condition,1,3) %in% GI_diseases ~1, 
                                 substr(other_condition_1,1,3) %in% GI_diseases ~1, 
                                 substr(other_condition_2,1,3) %in%  GI_diseases ~1, 
                                 substr(other_condition_3,1,3) %in% GI_diseases ~1, 
                                 substr(other_condition_4,1,3) %in%  GI_diseases ~1, 
                                 substr(other_condition_5,1,3) %in% GI_diseases ~1, 
                                 substr(main_condition,1,4) %in% GI_diseases ~1, 
                                 substr(other_condition_1,1,4) %in% GI_diseases ~1, 
                                 substr(other_condition_2,1,4) %in%  GI_diseases ~1, 
                                 substr(other_condition_3,1,4) %in% GI_diseases ~1, 
                                 substr(other_condition_4,1,4) %in%  GI_diseases ~1, 
                                 substr(other_condition_5,1,4) %in% GI_diseases ~1, 
                                 T~0),
         liver  = case_when(substr(main_condition,1,3) %in% Liver ~1, 
                            substr(other_condition_1,1,3) %in% Liver ~1, 
                            substr(other_condition_2,1,3) %in% Liver ~1,  
                            substr(other_condition_3,1,3) %in%  Liver ~1,  
                            substr(other_condition_4,1,3) %in% Liver ~1, 
                            substr(other_condition_5,1,3) %in%  Liver ~1, 
                            T~0),
         skin   = case_when(substr(main_condition,1,3) %in% Skin  ~1, 
                            substr(other_condition_1,1,3) %in% Skin  ~1, 
                            substr(other_condition_2,1,3) %in% Skin  ~1, 
                            substr(other_condition_3,1,3) %in% Skin  ~1, 
                            substr(other_condition_4,1,3) %in% Skin  ~1, 
                            substr(other_condition_5,1,3) %in% Skin  ~1, 
                            substr(main_condition,1,4) %in% Skin  ~1, 
                            substr(other_condition_1,1,4) %in% Skin  ~1, 
                            substr(other_condition_2,1,4) %in% Skin  ~1, 
                            substr(other_condition_3,1,4) %in% Skin  ~1, 
                            substr(other_condition_4,1,4) %in% Skin  ~1, 
                            substr(other_condition_5,1,4) %in% Skin  ~1, T~0),
         immune_joint_conn  = case_when(substr(main_condition,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_1,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_2,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_3,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_4,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_5,1,3) %in%  Immune_joint_conn ~1, 
                                        T~0),
         kidney  = case_when(substr(main_condition,1,3) %in% Kidney ~1, 
                             substr(other_condition_1,1,3) %in% Kidney ~1, 
                             substr(other_condition_2,1,3) %in%  Kidney ~1, 
                             substr(other_condition_3,1,3) %in% Kidney ~1, 
                             substr(other_condition_4,1,3) %in% Kidney ~1, 
                             substr(other_condition_5,1,3) %in% Kidney ~1, 
                             T~0),
         pelvic_genital_dis  = case_when(substr(main_condition,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_1,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_2,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_3,1,3) %in%  pelvic_genital_dis ~1, 
                                         substr(other_condition_4,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_5,1,3) %in%  pelvic_genital_dis ~1, 
                                         T~0),
  ) %>% 
  group_by(upi_number, cis_marker) %>%
  summarise(admission_type = first(admission_type),
            admission_date = first_(admission_date),
            discharge_date = last_(discharge_date),
            asthma = max_(asthma),
            cancer = max_(cancer), 
            diabetes= max_(diabetes),
            demyelinating_NM = max_(demyelinating_NM ),
            gi_disease = max_(gi_disease),
            haem  =max_(haem), 
            immune_joint_conn = max_(immune_joint_conn),
            kidney = max_(kidney),
            hypertension= max_(hypertension),
            liver=max_(liver), 
            pelvic_genital_dis = max_(pelvic_genital_dis), 
            thyroid = max_(thyroid),
            skin = max_(skin),
            vte = max_(vte) ) %>%
  mutate(emergency_admission = case_when(admission_type>=30 ~1, T~0))
##smr04
smr04 <- data_smr04_comorbs %>% 
  mutate(cancer = case_when(substr(main_condition,1,3) %in% Cancer ~1, 
                            substr(other_condition_1,1,3) %in%  Cancer ~1,  
                            substr(other_condition_2,1,3) %in%  Cancer ~1, 
                            substr(other_condition_3,1,3) %in%  Cancer ~1, 
                            substr(other_condition_4,1,3) %in%  Cancer ~1, 
                            substr(other_condition_5,1,3) %in%  Cancer ~1, 
                            T~0)) %>% 
  mutate(haem = case_when(substr(main_condition,1,3) %in% Haematological ~1, 
                          substr(other_condition_1,1,3) %in%  Haematological ~1, 
                          substr(other_condition_2,1,3) %in%  Haematological ~1, 
                          substr(other_condition_3,1,3) %in%  Haematological ~1, 
                          substr(other_condition_4,1,3) %in% Haematological ~1, 
                          substr(other_condition_5,1,3) %in% Haematological ~1, 
                          substr(main_condition,1,4) %in% Haematological ~1, 
                          substr(other_condition_1,1,4) %in%  Haematological ~1, 
                          substr(other_condition_2,1,4) %in%  Haematological ~1, 
                          substr(other_condition_3,1,4) %in%  Haematological ~1, 
                          substr(other_condition_4,1,4) %in% Haematological ~1, 
                          substr(other_condition_5,1,4) %in% Haematological ~1, 
                          T~0), 
         thyroid =case_when(substr(main_condition,1,3) %in% Thyroid ~1, 
                            substr(other_condition_1,1,3) %in%  Thyroid ~1, 
                            substr(other_condition_2,1,3) %in%  Thyroid ~1, 
                            substr(other_condition_3,1,3) %in%  Thyroid ~1, 
                            substr(other_condition_4,1,3) %in% Thyroid ~1, 
                            substr(other_condition_5,1,3) %in% Thyroid ~1, 
                            substr(main_condition,1,4) %in% Thyroid ~1, 
                            substr(other_condition_1,1,4) %in%  Thyroid ~1, 
                            substr(other_condition_2,1,4) %in%  Thyroid ~1, 
                            substr(other_condition_3,1,4) %in%  Thyroid ~1, 
                            substr(other_condition_4,1,4) %in% Thyroid ~1, 
                            substr(other_condition_5,1,4) %in% Thyroid ~1, 
                            T~0), 
         diabetes  = case_when(substr(main_condition,1,3) %in% Diabetes ~1, 
                               substr(other_condition_1,1,3) %in% Diabetes ~1, 
                               substr(other_condition_2,1,3) %in%   Diabetes ~1, 
                               substr(other_condition_3,1,3) %in%   Diabetes ~1, 
                               substr(other_condition_4,1,3) %in%  Diabetes ~1, 
                               substr(other_condition_5,1,3) %in%  Diabetes ~1, 
                               substr(main_condition,1,4) %in% Diabetes ~1, 
                               substr(other_condition_1,1,4) %in% Diabetes ~1, 
                               substr(other_condition_2,1,4) %in%   Diabetes ~1, 
                               substr(other_condition_3,1,4) %in%   Diabetes ~1, 
                               substr(other_condition_4,1,4) %in%  Diabetes ~1, 
                               substr(other_condition_5,1,4) %in%  Diabetes ~1, 
                               T~0),
         demyelinating_NM  = case_when(substr(main_condition,1,3) %in% Demyelinating_NM ~1, 
                                       substr(other_condition_1,1,3) %in% Demyelinating_NM ~1, 
                                       substr(other_condition_2,1,3) %in%  Demyelinating_NM ~1, 
                                       substr(other_condition_3,1,3) %in%  Demyelinating_NM ~1, 
                                       substr(other_condition_4,1,3) %in%  Demyelinating_NM ~1, 
                                       substr(other_condition_5,1,3) %in% Demyelinating_NM ~1, 
                                       T~0),
         hypertension  = case_when(substr(main_condition,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_1,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_2,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_3,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_4,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_5,1,3) %in% Hypertension ~1, 
                                   T~0),
         vte  = case_when(substr(main_condition,1,3) %in% VTE ~1, 
                          substr(other_condition_1,1,3) %in% VTE ~1, 
                          substr(other_condition_2,1,3) %in% VTE ~1, 
                          substr(other_condition_3,1,3) %in% VTE ~1, 
                          substr(other_condition_4,1,3) %in% VTE ~1, 
                          substr(other_condition_5,1,3) %in%  VTE ~1,  
                          T~0),
         asthma  = case_when(substr(main_condition,1,3) %in% Asthma ~1, 
                             substr(other_condition_1,1,3) %in% Asthma ~1, 
                             substr(other_condition_2,1,3) %in%  Asthma ~1, 
                             substr(other_condition_3,1,3) %in%  Asthma ~1, 
                             substr(other_condition_4,1,3) %in%  Asthma ~1, 
                             substr(other_condition_5,1,3) %in%  Asthma ~1, 
                             substr(main_condition,1,4) %in% Asthma ~1, 
                             substr(other_condition_1,1,4) %in% Asthma ~1, 
                             substr(other_condition_2,1,4) %in%  Asthma ~1, 
                             substr(other_condition_3,1,4) %in%  Asthma ~1, 
                             substr(other_condition_4,1,4) %in%  Asthma ~1, 
                             substr(other_condition_5,1,4) %in%  Asthma ~1, 
                             T~0),
         gi_disease  = case_when(substr(main_condition,1,3) %in% GI_diseases ~1, 
                                 substr(other_condition_1,1,3) %in% GI_diseases ~1, 
                                 substr(other_condition_2,1,3) %in%  GI_diseases ~1, 
                                 substr(other_condition_3,1,3) %in% GI_diseases ~1, 
                                 substr(other_condition_4,1,3) %in%  GI_diseases ~1, 
                                 substr(other_condition_5,1,3) %in% GI_diseases ~1, 
                                 substr(main_condition,1,4) %in% GI_diseases ~1, 
                                 substr(other_condition_1,1,4) %in% GI_diseases ~1, 
                                 substr(other_condition_2,1,4) %in%  GI_diseases ~1, 
                                 substr(other_condition_3,1,4) %in% GI_diseases ~1, 
                                 substr(other_condition_4,1,4) %in%  GI_diseases ~1, 
                                 substr(other_condition_5,1,4) %in% GI_diseases ~1, 
                                 T~0),
         liver  = case_when(substr(main_condition,1,3) %in% Liver ~1, 
                            substr(other_condition_1,1,3) %in% Liver ~1, 
                            substr(other_condition_2,1,3) %in% Liver ~1,  
                            substr(other_condition_3,1,3) %in%  Liver ~1,  
                            substr(other_condition_4,1,3) %in% Liver ~1, 
                            substr(other_condition_5,1,3) %in%  Liver ~1, 
                            T~0),
         skin   = case_when(substr(main_condition,1,3) %in% Skin  ~1, 
                            substr(other_condition_1,1,3) %in% Skin  ~1, 
                            substr(other_condition_2,1,3) %in% Skin  ~1, 
                            substr(other_condition_3,1,3) %in% Skin  ~1, 
                            substr(other_condition_4,1,3) %in% Skin  ~1, 
                            substr(other_condition_5,1,3) %in% Skin  ~1, 
                            substr(main_condition,1,4) %in% Skin  ~1, 
                            substr(other_condition_1,1,4) %in% Skin  ~1, 
                            substr(other_condition_2,1,4) %in% Skin  ~1, 
                            substr(other_condition_3,1,4) %in% Skin  ~1, 
                            substr(other_condition_4,1,4) %in% Skin  ~1, 
                            substr(other_condition_5,1,4) %in% Skin  ~1, T~0),
         immune_joint_conn  = case_when(substr(main_condition,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_1,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_2,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_3,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_4,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_5,1,3) %in%  Immune_joint_conn ~1, 
                                        T~0),
         kidney  = case_when(substr(main_condition,1,3) %in% Kidney ~1, 
                             substr(other_condition_1,1,3) %in% Kidney ~1, 
                             substr(other_condition_2,1,3) %in%  Kidney ~1, 
                             substr(other_condition_3,1,3) %in% Kidney ~1, 
                             substr(other_condition_4,1,3) %in% Kidney ~1, 
                             substr(other_condition_5,1,3) %in% Kidney ~1, 
                             T~0),
         pelvic_genital_dis  = case_when(substr(main_condition,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_1,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_2,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_3,1,3) %in%  pelvic_genital_dis ~1, 
                                         substr(other_condition_4,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_5,1,3) %in%  pelvic_genital_dis ~1, 
                                         T~0)) %>% 
  group_by(upi_number, cis_marker) %>%
  summarise(admission_type = first(admission_type),
            admission_date = first_(admission_date),
            discharge_date = last_(discharge_date),
            asthma = max_(asthma),
            cancer = max_(cancer), 
            diabetes= max_(diabetes),
            demyelinating_NM = max_(demyelinating_NM ),
            gi_disease = max_(gi_disease),
            haem  =max_(haem), 
            immune_joint_conn = max_(immune_joint_conn),
            kidney = max_(kidney),
            hypertension= max_(hypertension),
            liver=max_(liver), 
            pelvic_genital_dis = max_(pelvic_genital_dis), 
            thyroid = max_(thyroid),
            skin = max_(skin),
            vte = max_(vte) ) %>%
  mutate(emergency_admission = case_when(admission_type>=30 ~1, T~0))

##smr02
smr02 <- data_smr02_comorb %>% 
  mutate(cancer = case_when(substr(main_condition,1,3) %in% Cancer ~1, 
                            substr(other_condition_1,1,3) %in%  Cancer ~1,  
                            substr(other_condition_2,1,3) %in%  Cancer ~1, 
                            substr(other_condition_3,1,3) %in%  Cancer ~1, 
                            substr(other_condition_4,1,3) %in%  Cancer ~1, 
                            substr(other_condition_5,1,3) %in%  Cancer ~1,
                            substr(indication_for_operative_del,1,3) %in%  Cancer ~1,
                            T~0)) %>% 
 mutate(haem_all = case_when(substr(main_condition,1,3) %in% Haematological ~1, 
                          substr(other_condition_1,1,3) %in%  Haematological ~1, 
                          substr(other_condition_2,1,3) %in%  Haematological ~1, 
                          substr(other_condition_3,1,3) %in%  Haematological ~1, 
                          substr(other_condition_4,1,3) %in% Haematological ~1, 
                          substr(other_condition_5,1,3) %in% Haematological ~1, 
                          substr(indication_for_operative_del,1,3) %in% Haematological ~1,
                          substr(main_condition,1,4) %in% Haematological ~1, 
                          substr(other_condition_1,1,4) %in%  Haematological ~1, 
                          substr(other_condition_2,1,4) %in%  Haematological ~1, 
                          substr(other_condition_3,1,4) %in%  Haematological ~1, 
                          substr(other_condition_4,1,4) %in% Haematological ~1, 
                          substr(other_condition_5,1,4) %in% Haematological ~1, 
                          substr(indication_for_operative_del,1,4) %in% Haematological ~1,
                          T~0), 
        haem =  case_when(substr(main_condition,1,3) %in% Heam_excl_anaemia ~1, 
                          substr(other_condition_1,1,3) %in%  Heam_excl_anaemia ~1, 
                          substr(other_condition_2,1,3) %in%  Heam_excl_anaemia ~1, 
                          substr(other_condition_3,1,3) %in%  Heam_excl_anaemia ~1, 
                          substr(other_condition_4,1,3) %in% Heam_excl_anaemia ~1, 
                          substr(other_condition_5,1,3) %in% Heam_excl_anaemia ~1, 
                          substr(indication_for_operative_del,1,3) %in% Heam_excl_anaemia ~1,
                          substr(main_condition,1,4) %in% Heam_excl_anaemia ~1, 
                          substr(other_condition_1,1,4) %in%  Heam_excl_anaemia ~1, 
                          substr(other_condition_2,1,4) %in%  Heam_excl_anaemia ~1, 
                          substr(other_condition_3,1,4) %in%  Heam_excl_anaemia ~1, 
                          substr(other_condition_4,1,4) %in% Heam_excl_anaemia ~1, 
                          substr(other_condition_5,1,4) %in% Heam_excl_anaemia ~1, 
                          substr(indication_for_operative_del,1,4) %in% Heam_excl_anaemia ~1,
                          T~0), 
         thyroid =case_when(substr(main_condition,1,3) %in% Thyroid ~1, 
                            substr(other_condition_1,1,3) %in%  Thyroid ~1, 
                            substr(other_condition_2,1,3) %in%  Thyroid ~1, 
                            substr(other_condition_3,1,3) %in%  Thyroid ~1, 
                            substr(other_condition_4,1,3) %in% Thyroid ~1, 
                            substr(other_condition_5,1,3) %in% Thyroid ~1,
                            substr(indication_for_operative_del,1,3) %in% Thyroid ~1,
                            substr(main_condition,1,4) %in% Thyroid ~1, 
                            substr(other_condition_1,1,4) %in%  Thyroid ~1, 
                            substr(other_condition_2,1,4) %in%  Thyroid ~1, 
                            substr(other_condition_3,1,4) %in%  Thyroid ~1, 
                            substr(other_condition_4,1,4) %in% Thyroid ~1, 
                            substr(other_condition_5,1,4) %in% Thyroid ~1, 
                            substr(indication_for_operative_del,1,4) %in% Thyroid ~1,
                            T~0), 
         diabetes  = case_when(substr(main_condition,1,3) %in% Diabetes ~1, 
                               substr(other_condition_1,1,3) %in% Diabetes ~1, 
                               substr(other_condition_2,1,3) %in%  Diabetes ~1, 
                               substr(other_condition_3,1,3) %in%  Diabetes ~1, 
                               substr(other_condition_4,1,3) %in%  Diabetes ~1, 
                               substr(other_condition_5,1,3) %in%  Diabetes ~1, 
                               substr(indication_for_operative_del,1,3) %in% Diabetes ~1,
                               substr(main_condition,1,4) %in% Diabetes ~1, 
                               substr(other_condition_1,1,4) %in% Diabetes ~1, 
                               substr(other_condition_2,1,4) %in%   Diabetes ~1, 
                               substr(other_condition_3,1,4) %in%   Diabetes ~1, 
                               substr(other_condition_4,1,4) %in%  Diabetes ~1, 
                               substr(other_condition_5,1,4) %in%  Diabetes ~1, 
                               substr(indication_for_operative_del,1,4) %in% Diabetes ~1,
                               T~0),
         demyelinating_NM  = case_when(substr(main_condition,1,3) %in% Demyelinating_NM ~1, 
                                       substr(other_condition_1,1,3) %in% Demyelinating_NM ~1, 
                                       substr(other_condition_2,1,3) %in%  Demyelinating_NM ~1, 
                                       substr(other_condition_3,1,3) %in%  Demyelinating_NM ~1, 
                                       substr(other_condition_4,1,3) %in%  Demyelinating_NM ~1, 
                                       substr(other_condition_5,1,3) %in% Demyelinating_NM ~1, 
                                       T~0),
         hypertension  = case_when(substr(main_condition,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_1,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_2,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_3,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_4,1,3) %in% Hypertension ~1, 
                                   substr(other_condition_5,1,3) %in% Hypertension ~1,
                                   substr(indication_for_operative_del,1,3) %in% Hypertension ~1,
                                   T~0),
         vte  = case_when(substr(main_condition,1,3) %in% VTE ~1, 
                          substr(other_condition_1,1,3) %in% VTE ~1, 
                          substr(other_condition_2,1,3) %in% VTE ~1, 
                          substr(other_condition_3,1,3) %in% VTE ~1, 
                          substr(other_condition_4,1,3) %in% VTE ~1, 
                          substr(other_condition_5,1,3) %in%  VTE ~1,  
                          substr(indication_for_operative_del,1,3) %in% VTE ~1,
                          T~0),
         asthma  = case_when(substr(main_condition,1,3) %in% Asthma ~1, 
                             substr(other_condition_1,1,3) %in% Asthma ~1, 
                             substr(other_condition_2,1,3) %in%  Asthma ~1, 
                             substr(other_condition_3,1,3) %in%  Asthma ~1, 
                             substr(other_condition_4,1,3) %in%  Asthma ~1, 
                             substr(other_condition_5,1,3) %in%  Asthma ~1, 
                             substr(indication_for_operative_del,1,3) %in% Asthma ~1,
                             substr(main_condition,1,4) %in% Asthma ~1, 
                             substr(other_condition_1,1,4) %in% Asthma ~1, 
                             substr(other_condition_2,1,4) %in%  Asthma ~1, 
                             substr(other_condition_3,1,4) %in%  Asthma ~1, 
                             substr(other_condition_4,1,4) %in%  Asthma ~1, 
                             substr(other_condition_5,1,4) %in%  Asthma ~1,
                             substr(indication_for_operative_del,1,4) %in% Asthma ~1,
                             T~0),
         gi_disease  = case_when(substr(main_condition,1,3) %in% GI_diseases ~1, 
                                 substr(other_condition_1,1,3) %in% GI_diseases ~1, 
                                 substr(other_condition_2,1,3) %in%  GI_diseases ~1, 
                                 substr(other_condition_3,1,3) %in% GI_diseases ~1, 
                                 substr(other_condition_4,1,3) %in%  GI_diseases ~1, 
                                 substr(other_condition_5,1,3) %in% GI_diseases ~1,
                                 substr(indication_for_operative_del,1,3) %in% GI_diseases ~1,
                                 substr(main_condition,1,4) %in% GI_diseases ~1, 
                                 substr(other_condition_1,1,4) %in% GI_diseases ~1, 
                                 substr(other_condition_2,1,4) %in%  GI_diseases ~1, 
                                 substr(other_condition_3,1,4) %in% GI_diseases ~1, 
                                 substr(other_condition_4,1,4) %in%  GI_diseases ~1, 
                                 substr(other_condition_5,1,4) %in% GI_diseases ~1, 
                                 substr(indication_for_operative_del,1,4) %in% GI_diseases ~1,
                                 T~0),
         liver  = case_when(substr(main_condition,1,3) %in% Liver ~1, 
                            substr(other_condition_1,1,3) %in% Liver ~1, 
                            substr(other_condition_2,1,3) %in% Liver ~1,  
                            substr(other_condition_3,1,3) %in%  Liver ~1,  
                            substr(other_condition_4,1,3) %in% Liver ~1, 
                            substr(other_condition_5,1,3) %in%  Liver ~1, 
                            substr(indication_for_operative_del,1,3) %in% Liver ~1,
                            T~0),
         skin   = case_when(substr(main_condition,1,3) %in% Skin  ~1, 
                            substr(other_condition_1,1,3) %in% Skin  ~1, 
                            substr(other_condition_2,1,3) %in% Skin  ~1, 
                            substr(other_condition_3,1,3) %in% Skin  ~1, 
                            substr(other_condition_4,1,3) %in% Skin  ~1, 
                            substr(other_condition_5,1,3) %in% Skin  ~1, 
                            substr(indication_for_operative_del,1,3) %in% Skin ~1,
                            substr(main_condition,1,4) %in% Skin  ~1, 
                            substr(other_condition_1,1,4) %in% Skin  ~1, 
                            substr(other_condition_2,1,4) %in% Skin  ~1, 
                            substr(other_condition_3,1,4) %in% Skin  ~1, 
                            substr(other_condition_4,1,4) %in% Skin  ~1, 
                            substr(other_condition_5,1,4) %in% Skin  ~1, 
                            substr(indication_for_operative_del,1,4) %in% Skin ~1,T~0),
         immune_joint_conn  = case_when(substr(main_condition,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_1,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_2,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_3,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_4,1,3) %in% Immune_joint_conn ~1, 
                                        substr(other_condition_5,1,3) %in%  Immune_joint_conn ~1, 
                                        substr(indication_for_operative_del,1,3) %in% Immune_joint_conn ~1,
                                        T~0),
         kidney  = case_when(substr(main_condition,1,3) %in% Kidney ~1, 
                             substr(other_condition_1,1,3) %in% Kidney ~1, 
                             substr(other_condition_2,1,3) %in%  Kidney ~1, 
                             substr(other_condition_3,1,3) %in% Kidney ~1, 
                             substr(other_condition_4,1,3) %in% Kidney ~1, 
                             substr(other_condition_5,1,3) %in% Kidney ~1, 
                             substr(indication_for_operative_del,1,3) %in% Kidney ~1,
                             T~0),
         pelvic_genital_dis  = case_when(substr(main_condition,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_1,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_2,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_3,1,3) %in%  pelvic_genital_dis ~1, 
                                         substr(other_condition_4,1,3) %in% pelvic_genital_dis ~1, 
                                         substr(other_condition_5,1,3) %in%  pelvic_genital_dis ~1, 
                                         substr(indication_for_operative_del,1,3) %in% pelvic_genital_dis ~1,
                                         T~0)) 

###########################################
smr_all <- rbind(smr01, smr04, smr02)
smr_all <-smr_all %>% filter(asthma==1| cancer==1 | diabetes==1 | demyelinating_NM==1 | 
                   gi_disease==1 | haem==1 | immune_joint_conn==1 | kidney==1 | 
                  hypertension==1 | liver==1 |pelvic_genital_dis==1 | 
                    thyroid==1 | skin==1 | vte==1 ) %>%
  select(upi_number, admission_date, discharge_date, asthma, cancer, diabetes, demyelinating_NM, 
         gi_disease, haem, immune_joint_conn,kidney, hypertension, liver, pelvic_genital_dis, 
         thyroid, skin, vte)

saveRDS(smr_all, paste0(folder_data_path, "smra_extracts/smr_comorbidities.rds"))
###lookback period

